In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/movies_metadata.csv')

In [ ]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
df=df.drop_duplicates().reset_index(drop=True)

In [ ]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
df =df[['title','genres','overview','vote_average','tagline','popularity']]

In [ ]:
df.head(
)

,title,genres,overview,vote_average,tagline,popularity
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",7.7,NaN,21.946943
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,6.9,Roll the dice and unleash the excitement!,17.015539
2,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,6.5,Still Yelling. Still Fighting. Still Ready for...,11.7129
3,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",6.1,Friends are the people who let you be yourself...,3.859495
4,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,5.7,Just When His World Is Back To Normal... He's ...,8.387519

In [ ]:
df.isnull().sum()

title               6
genres              0
overview          954
vote_average        6
tagline         25045
popularity          5
dtype: int64

In [ ]:
df=df.dropna(subset=['title'])

In [ ]:
df['overview'] = df['overview'].fillna('')

In [ ]:
df.iloc[0]['genres']
import ast

In [ ]:
df['genres'] = df['genres'].apply(lambda x: " ".join([i['name'] for i in ast.literal_eval(x)]) if x != '[]' else '')

In [ ]:
df['tagline'] = df['tagline'].fillna('')

In [ ]:
df['tags'] = df['overview'] + ' ' + df['genres'] + ' ' + df['tagline']

In [ ]:
df.head()

,title,genres,overview,vote_average,tagline,popularity,tags
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",7.7,,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,6.9,Roll the dice and unleash the excitement!,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,6.5,Still Yelling. Still Fighting. Still Ready for...,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",6.1,Friends are the people who let you be yourself...,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,5.7,Just When His World Is Back To Normal... He's ...,8.387519,Just when George Banks has recovered from his ...

In [ ]:
df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [ ]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [ ]:
def preprocess_text(text):
    text = str(text).lower()
    text = re.sub('[^a-zA-Z]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    words = text.split()
    words = [word for word in words if word not in stop_words]
    words = [lemmatizer.lemmatize(word) for word in words]
    return " ".join(words)

In [ ]:
df['tags'] = df['tags'].fillna('').astype(str)
df['tags'] = df['tags'].apply(preprocess_text)

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult trapped inside game year living room alan hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [ ]:
df=df.reset_index(drop=True)

,title,genres,overview,vote_average,tagline,popularity,tags
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",7.7,,21.946943,led woody andy toy live happily room andy birt...
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,6.9,Roll the dice and unleash the excitement!,17.015539,sibling judy peter discover enchanted board ga...
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,6.5,Still Yelling. Still Fighting. Still Ready for...,11.7129,family wedding reignites ancient feud next doo...
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",6.1,Friends are the people who let you be yourself...,3.859495,cheated mistreated stepped woman holding breat...
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,5.7,Just When His World Is Back To Normal... He's ...,8.387519,george bank recovered daughter wedding receive...

In [ ]:
indices=pd.Series(df.index,index=df['title']).drop_duplicates()

np.int64(1)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
tfidf=TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')
tfidf_matrix=tfidf.fit_transform(df['tags'])

In [ ]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1585870 stored elements and shape (45447, 50000)>

In [ ]:
def recommend(title,n=10):
   if title not in indices:
     return "Movie not found"
   idx=indices[title]
   sim_score=cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
   similar_idx=sim_score.argsort()[::-1][1:n+1]
   return df['title'].iloc[similar_idx]

In [ ]:
recommend('Toy Story')

15344                                     Toy Story 3
2996                                      Toy Story 2
24512                                       Small Fry
10298                          The 40 Year Old Virgin
23832                     Andy Hardy's Blonde Trouble
29189                                      Hot Splash
43408                Andy Kaufman Plays Carnegie Hall
42702    Andy Peters: Exclamation Mark Question Point
8326                                        The Champ
3056                                  Man on the Moon
Name: title, dtype: object

In [ ]:
import pickle
pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))
pickle.dump(indices,open('indices.pkl','wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf,open('tfidf.pkl','wb'))